LIB_CSOURCES =       \
	affine.c     \
	angle.c      \
	bmp16_plot.c \
	display.c    \
	dma.c        \
	input.c      \
	interrupt.arm.c \
	lut_sinus.c  \
	m4.c         \
	object.c

LIB_ASOURCES =       \
	bios.s       \
	interrupt_asm.arm.s

